apiVersion: "v1"
kind: Pod
metadata:
  name: postgredb
  labels:
    name: "postgre"
    owner: "Rosered"
    version: "1.0"
spec:
  containers:
    - name: db
      image: postgres:10
      ports:
        - containerPort: 5432
          protocol: TCP
      env:
        - name: "POSTGRES_USER"
          value: "sa"
        - name: "POSTGRES_PASSWORD"
          value: "pass@word1"
      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: "volpostgre"
    - name: adminer
      image: dpage/pgadmin4
      ports:
        - containerPort: 80
          protocol: TCP
      env:
        - name: "PGADMIN_DEFAULT_EMAIL"
          value: "sa@sa.sa"
        - name: "PGADMIN_DEFAULT_PASSWORD"
          value: "pass@word1"
      volumeMounts:
      - mountPath: "/var/lib/root/.pgadmin"
        name: "voladmin"
  volumes:
    - name: "volpostgre"
      hostPath:
        path: "/var/lib/postgresql/data"
    - name: "voladmin"
      hostPath:
        path: "/var/lib/postgresql/root/.pgadmin"