apiVersion: v1
kind: Service
metadata:
  name: postgredb
  labels:
    name: "postgre"
    owner: "Rosered"
    version: "1.0"
spec:
  ports:
  - port: 80
    name: postgreadmin
    targetPort: 80
    protocol: TCP
    nodePort: 31880
  - port: 5432
    name: postgredb
    targetPort: 5432
    protocol: TCP
    nodePort: 31543
  type: NodePort
  selector:
    name: "postgre"
    owner: "Rosered"
    version: "1.0"